Scatter/Contour plot functionality
varlociraptor/varlociraptor pull request #178
Opened 2021-06-10 14:13 UTC by jafors

A function to plot a scatter plot with an overlaying contour plot between two sample groups. Multiple samples can be plotted against one fixed sample.

2021-06-11 13:51 UTC, johanneskoester requested changes

2021-06-11 13:51 UTC, johanneskoester commented on src/estimation/sample_variants.rs
> +        let mut rec = bcf.empty_record();
Just iterate over `bcf.records()`.

2021-06-11 13:51 UTC, johanneskoester commented on src/estimation/sample_variants.rs
> +    }
Maybe do not talk about tumor/normal here but in general sample_a and sample_b?

2021-06-11 13:51 UTC, johanneskoester commented on src/cli.rs
> +        --tumor-sample tumor --normal-sample normal < calls.bcf | vg2svg > scatter.svg",
Can we have generic names instead of tumor/normal?

2021-06-11 13:51 UTC, johanneskoester commented on src/cli.rs
> +            default_value = "SOMATIC_TUMOR",
Here as well, keep it generic, not implying that this shall be only used for somatic variants. Although it of course makes most sense there, but nevertheless.

2021-06-11 13:52 UTC, johanneskoester commented
Thanks a lot! One more thing: can you please also fix the clippy lints that occur within your new commits (not the old ones from elsewhere).

2021-06-16 11:29 UTC, johanneskoester requested changes

2021-06-16 11:29 UTC, johanneskoester commented on src/cli.rs
> +            long = "sample-A",
Maybe just as positional arguments?

2021-06-21 13:50 UTC, johanneskoester approved these changes

2021-06-21 13:52 UTC, johanneskoester requested changes
Mhm, why are the alternative samples on the y-axis? Wouldn't it be more natural to have them on the y-axis?

2021-06-21 13:56 UTC, jafors commented
Yes, you are right. It looked "nicer" to me in the examples I tried. But that's probably just some weird bias and my own taste. Logically, it makes probably more sense the other way round.

2021-06-24 09:23 UTC, johanneskoester approved these changes

2021-06-24 09:23 UTC, merged