Feat/methylation candidates
varlociraptor/varlociraptor pull request #394
Opened 2023-08-16 11:38 UTC by Addimator

### Description

feat: Methylation candidates

### QC

* [ ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [ ] The documentation at https://github.com/varlociraptor/varlociraptor.github.io is updated in a separate PR to reflect the changes or this is not necessary (e.g. if the change does neither modify the calling grammar nor the behavior or functionalities of Varlociraptor).

2023-08-16 12:02 UTC, Addimator commented
In order to run the test successfully, I have the required local file at test_meth_ev_1/genome.fasta. However, the current .gitignore configuration prevents the upload of this file, leading to test failures. I'm unsure whether adding an exception directly to the .gitignore is the right approach, considering there are no visible exceptions for files like candidates.matched.bcf.

2023-08-17 08:45 UTC, johanneskoester requested changes

2023-08-17 08:45 UTC, johanneskoester commented on src/cli.rs
> +    Candidates {
```suggestion
    MethylationCandidates {
```

2023-08-17 08:45 UTC, johanneskoester commented on src/cli.rs
> +        name = "candidates",
```suggestion
        name = "methylation-candidates",
```

2023-08-17 08:45 UTC, johanneskoester commented on src/cli.rs
> +        #[structopt(name = "output", parse(from_os_str), help = "Output VCF File")]
```suggestion
        #[structopt(name = "output", parse(from_os_str), help = "Output BCF File")]
```

2023-08-17 08:45 UTC, johanneskoester commented on src/candidates/methylation.rs
> +use std::path::PathBuf;
```suggestion
use std::path::PathBuf;
use anyhow::Result;
use itertools::Itertools;
```

2023-08-17 08:45 UTC, johanneskoester commented on src/candidates/methylation.rs
> +    let fasta_file: File = File::open(infasta).expect("Unable to open");
```suggestion
pub fn find_candidates(infasta: PathBuf, outvcf: Option<PathBuf>) -> Result<()> {
    // Open FASTA File
    let fasta_file: File = File::open(infasta).with_context(|| format!("Error reading FASTA file {infasta}"))?;
```

2023-08-17 08:45 UTC, johanneskoester commented on src/candidates/methylation.rs
> +    for rec in data {
```suggestion
    for (contig, pos) in data {
```

2023-08-17 08:45 UTC, johanneskoester commented on src/candidates/methylation.rs
> +        }
```suggestion
        vcf_writer.write(&record).with_context(|| format!("failed to write BCF record with methylation candidate")?;
```

2023-08-17 08:45 UTC, johanneskoester commented on src/candidates/methylation.rs
> +
```suggestion
```

2023-08-17 08:45 UTC, johanneskoester commented on src/candidates/methylation.rs
> +    for result in reader.records() {
```suggestion
    // TODO: consider using an IndexedReader to write the BCF header first
    // and then write the methylation candidate records on the fly while reading
    // the FASTA.
    for result in reader.records() {
```

2023-08-17 08:45 UTC, johanneskoester commented on src/candidates/methylation.rs
> +pub fn find_candidates(infasta: PathBuf, outvcf: Option<PathBuf>) {
```suggestion
pub fn find_candidates(infasta: PathBuf, outvcf: Option<PathBuf>) {
    // TODO: add implementation for other methylation types (CHH, ..., given via a pattern arg)
```

2023-08-17 14:44 UTC, johanneskoester commented on src/candidates/methylation.rs
> +use std::path::PathBuf;
Above there are still some compiler warnings (unused imports)

2023-08-28 11:03 UTC, johanneskoester approved these changes

2023-08-28 11:03 UTC, merged